### ISSUE TITLE
"Next week, Mon 9 AM" - bad timezone

### ISSUE THREAD

**Issue by tuxmartin** [AddReminders/Reminders-in-RocketChat#12]
Hi,
I tried "Next week, Mon 9 AM"  and there is a problem with timezone.

I have timezone Europe/Prague and message arrived at 07:00 Europe/Prague time. Not 09:00 Europe/Prague.

It is not very important.

**Comment by murtaza98** [comment]
Hey, Just an update - there indeed was a bug with this "Next week, Mon 9AM" action. I've managed to fix it over here https://github.com/AddReminders/Reminders-in-RocketChat/releases/tag/2.4.0 and has been submitted to the RocketChat marketplace. But the review is still pending by the team so it's now publically available. However, if you don't wish to wait until it is available on the marketplace, then you may install it manually on your server :smile: (Info in above link)

Thanks for reporting this issue and helping improve this app :people_hugging:

**Comment by murtaza98** [comment]
Released with Version 2.7 on marketplace. Version also available here for offline install -> https://github.com/AddReminders/Reminders-in-RocketChat/releases/tag/2.7.0
