### ISSUE TITLE
Feature Request: Make Botname und Icon editable 

### ISSUE THREAD

**Issue by saschafoerster** [AddReminders/Reminders-in-RocketChat#2]
I would like to customize our bot to german, with his own name and logo :)

**Comment by murtaza98** [comment]
Hi @saschafoerster The bot is just a usual Rocket.Chat user, so you should be able to change its name and logo from `Admin -> Users` panel. Let me know if you face any issue

**Comment by saschafoerster** [comment]
Thank you! I hoped that I could create one single bot user for all the apps, but now I saw, there where already plenty of other but users, so I was fine with renaming and changing the icon.
