### ISSUE TITLE
Add "next week" reminder

### ISSUE THREAD

**Issue by tuxmartin** [AddReminders/Reminders-in-RocketChat#7]
Hello,

can you please add "Remind me about this: Next week" like in Slack to the predefined list of reminders?

In Slack, slackbot user send reminder message for "next week" every Monday at 09AM.

I think it will be very useful,
thanks.

![2022-06-10-144910_1920x1080_scrot](https://user-images.githubusercontent.com/1219067/173068622-cdc3e543-7017-41f3-b6d1-5657f223c448.png)

![43573372-e1c16026-9641-11e8-9ce4-890d875b1292](https://user-images.githubusercontent.com/1219067/173068629-55c3ca92-4683-4ef5-9806-c93c26e5dbcd.png)

**Comment by murtaza98** [comment]
Sure, this sounds useful. Will make this part of next release :+1:

**Comment by murtaza98** [comment]
Released with [version 2.3.0](https://github.com/AddReminders/reminderApp/releases/tag/2.3.0)
