### ISSUE TITLE
Support 24 hours time format

### ISSUE THREAD

**Issue by murtaza98** [AddReminders/Reminders-in-RocketChat#9]
At the moment, we only display time in 12-hour format. With this new enhancement, we'd allow users to change this to 24 hours format as per their preference.

**Comment by tuxmartin** [comment]
@murtaza98 hello, do you have a time estimate for this issue? When could it be finished?

**Comment by murtaza98** [comment]
Hey, sorry for the delay. Let me try to analyze this issue and get back by end of this week. Appreciate your patience :raised_hands:

**Comment by murtaza98** [comment]
Hi folks, I appreciate your patience :pray: I investigated this feature request and found that it should be pretty straightforward to implement because [the library used by this app](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat) for formatting already has support for 24 hours clock
![image](https://user-images.githubusercontent.com/34130764/202920004-2e68d7c7-363c-4463-b7cd-acf2479b644b.png)

I tried hard-coding this value and ran some tests locally, which seems to work pretty well. So the only thing left is adding an interface within the app to allow users to select their time formatting preference, which I'll try to wrap up tomorrow and then create a release and share it with you guys :hugs:

**Comment by murtaza98** [comment]
Hi @tuxmartin This new feature has been implemented in [this upcoming release](https://github.com/AddReminders/Reminders-in-RocketChat/releases/tag/2.5.0). I'm gonna use this week to test this feature on the open server and then if all looks good then I'll submit this version to the marketplace next week. So expect this change to be out on the marketplace by mid-next month. 

Also, if possible please help us test this change and report any issues :pray: Here you can find [the pre-release](https://github.com/AddReminders/Reminders-in-RocketChat/releases/tag/2.5.0)

Here's the summary of the changes:

A workspace-level setting to allow admins to setup a default timezone preference for all its users:
![image](https://user-images.githubusercontent.com/34130764/203386028-7f88bb42-4ad4-4604-b8dc-3e95e54a4cf0.png)

And if a user wishes to override their preference, then they can do it via `/remind help` command 
![image](https://user-images.githubusercontent.com/34130764/203386349-b5c8a3b2-ad11-4e22-82e1-378194c41552.png)

**Comment by murtaza98** [comment]
Released with Version 2.7 on marketplace. Version also available here for offline install -> https://github.com/AddReminders/Reminders-in-RocketChat/releases/tag/2.7.0

Thanks you for suggestion :raised_hands:
